version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data

#  api:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
#    volumes:
#      - .:/api
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db

volumes:
  db:
    driver: local